apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    trains: elasticsearch
    platform: trains
  name: elasticsearch
  namespace: {{ .Values.trains.namespace }}
spec:
  replicas: 1
  minReadySeconds: 15
  progressDeadlineSeconds: 180
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        trains: elasticsearch
        platform: trains
    spec:
      initContainers:
      - name: set-dir-owner
        image: busybox:1.29.2
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
        volumeMounts:
        - name: elasticsearch-hostpath
          mountPath: /usr/share/elasticsearch/data
      containers:
      - env:
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.name
          value: trains
        - name: cluster.routing.allocation.node_initial_primaries_recoveries
          value: "500"
        - name: discovery.zen.minimum_master_nodes
          value: "1"
        - name: http.compression_level
          value: "7"
        - name: node.ingest
          value: "true"
        - name: node.name
          value: trains
        - name: reindex.remote.whitelist
          value: '*.*'
        - name: script.inline
          value: "true"
        - name: script.painless.regex.enabled
          value: "true"
        - name: script.update
          value: "true"
        - name: thread_pool.bulk.queue_size
          value: "2000"
        - name: thread_pool.search.queue_size
          value: "10000"
        - name: xpack.monitoring.enabled
          value: "false"
        - name: xpack.security.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: {{ .Values.elasticsearch.esJavaOpts }}
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
        name: elasticsearch
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-hostpath
      restartPolicy: Always
      nodeSelector:
        {{ .Values.trains.nodeSelector}}
      volumes:
      - name: elasticsearch-hostpath
        hostPath:
          path: /usr/share/elasticsearch/data